<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'View Compare' => 'Lihat Perbandingan',
  'View Turunan class' => 'Lihat Kelas Turunan',
  'Are you sure to delete this item?' => '',
  'Bad Request' => '',
  'Browse code' => '',
  'Create New' => '',
  'Create New Data User' => '',
  'Data successfully saved!' => 'Data Berhasil di simpan !',
  'Email' => '',
  'Extensions' => '',
  'Hello' => '',
  'Home' => '',
  'Lihat turunannya' => '',
  'List Data' => '',
  'Load Model FORM(print_r($form)' => '',
  'Load Model(print_r($data1)' => '',
  'Load Model(print_r($model)' => '',
  'Load Model(print_r($model->search())' => '',
  'Load Model(print_r($res_criteria)' => '',
  'Load Model(print_r($res_criteria2)' => '',
  'Load POST&GET VARIABLE' => '',
  'Login' => '',
  'Logout' => '',
  'Manage Persons' => '',
  'New' => '',
  'New Data User' => '',
  'New User' => '',
  'READ with pure php code' => '',
  'Result' => '',
  'Sample - find() with 1 Condition' => '',
  'Sample - findAll() with 2 Condition' => '',
  'Sample - new CDbCriteria' => '',
  'View Skema - CActiveDataProvider' => '',
  'View code' => '',
  'view array' => '',
);
